stapp01 ansible_host=172.16.238.10 ansible_ssh_pass=Ir0nM@n  ansible_user=tony

stapp02 ansible_host=172.16.238.11 ansible_ssh_pass=Am3ric@  ansible_user=steve

stapp03 ansible_host=172.16.238.12 ansible_ssh_pass=BigGr33n  ansible_user=banner


- name: Ansible copy

  hosts: all

  become: yes

  tasks:

    - name: copy index.html to sysops folder

      copy: src=/usr/src/sysops/index.html dest=/opt/sysops



ansible all -a "ls -ltr /opt/sysops" -i inventory
